application: ingoingoingo23 
version: 1
runtime: go
api_version: go1

inbound_services:
- channel_presence

handlers:
- url: /rest/.*
  script: _go_app
- url: /_ah/channel/.*
  script: _go_app


- url: /static
  static_dir: static
